version: "3.5"
services:
  server:
    image: vsomeip
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: "server"
    privileged: true
    tty: true
    cap_add:
      - ALL
    networks:
      vsomeip-network:
        ipv4_address: 192.168.1.10
  client:
    image: vsomeip
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: "client"
    privileged: true
    tty: true
    cap_add:
      - ALL
    networks:
      vsomeip-network:
        ipv4_address: 192.168.1.20

networks:
  vsomeip-network:
    driver: bridge
    driver_opts: 
      com.docker.network.bridge.name: "vsomeip-nw"
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
